<a href="https://colab.research.google.com/github/ayush572/House_price_prediction_model/blob/main/House_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
#New training model started from here
#first run this cell please
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#One hot encoding done here
#Training of model
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/dataset/train.csv')
dummies=pd.get_dummies(df, columns=['MSZoning','HeatingQC','CentralAir','BsmtQual','BsmtCond','ExterQual','Exterior1st','RoofStyle','KitchenQual','Street','LandContour','GarageType','Utilities','LotConfig','FireplaceQu','GarageQual','GarageCond','BsmtFinType1','LandSlope','LotShape','Condition1','PoolQC','Fence','MiscFeature','SaleType','BldgType','HouseStyle','SaleCondition','RoofMatl'], drop_first=True)
y=df.SalePrice
y=y.to_numpy()
df=df.drop(['SalePrice','Id','MSZoning','CentralAir','Electrical','BldgType','HouseStyle','Heating','Street','HeatingQC','BsmtFinType2','BsmtQual','Alley','Functional','BsmtFinType1','BsmtCond','Foundation','SaleCondition','LandContour','ExterQual','Fireplaces','FireplaceQu','GarageCond','GarageQual','LandSlope','Neighborhood','Condition1','Condition2','LotShape','PoolQC','Fence','SaleType','RoofMatl','MiscFeature','BsmtExposure','ExterCond','MasVnrType','Utilities','LotConfig','GarageFinish','PavedDrive','Exterior2nd','GarageType','Exterior1st','RoofStyle','KitchenQual'], axis=1)
df=pd.concat([dummies], axis=1)
df.drop(['Functional','Id','Alley','Neighborhood','Condition2','Exterior2nd','MasVnrType','ExterCond','Foundation','BsmtExposure','BsmtFinType2','Heating','Electrical','GarageFinish','PavedDrive'], axis=1, inplace=True)
df.drop(df.columns[36], inplace=True, axis=1)
df=df.fillna(df.mean())
#Here the specific columns have been removed, upon comparision with the TEST DATASET
df.drop(df.columns[[152,153,154,155]], axis=1, inplace=True)
df.drop(['HouseStyle_2.5Fin'], axis=1, inplace=True)
df.drop(['MiscFeature_TenC'], axis=1, inplace=True)
df.drop(['PoolQC_Fa'], axis=1, inplace=True)
df.drop(['GarageQual_Fa'], axis=1, inplace=True)
df.drop(['Utilities_NoSeWa'], axis=1, inplace=True)
df.drop(['Exterior1st_ImStucc','Exterior1st_Stone'], axis=1, inplace=True)
df.drop(['MSZoning_FV'], axis=1, inplace=True)
df.head(5)
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 147 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   MSSubClass             1460 non-null   int64  
 1   LotFrontage            1460 non-null   float64
 2   LotArea                1460 non-null   int64  
 3   OverallQual            1460 non-null   int64  
 4   OverallCond            1460 non-null   int64  
 5   YearBuilt              1460 non-null   int64  
 6   YearRemodAdd           1460 non-null   int64  
 7   MasVnrArea             1460 non-null   float64
 8   BsmtFinSF1             1460 non-null   int64  
 9   BsmtFinSF2             1460 non-null   int64  
 10  BsmtUnfSF              1460 non-null   int64  
 11  TotalBsmtSF            1460 non-null   int64  
 12  1stFlrSF               1460 non-null   int64  
 13  2ndFlrSF               1460 non-null   int64  
 14  LowQualFinSF           1460 non-null   int64  
 15  GrL

In [ ]:
train=df[:1022]
test=df[1023:]
y1=y[:1022]
y2=y[1023:]

In [ ]:
trainarr=train.to_numpy()
testarr=test.to_numpy()
import numpy as np
#m,n=np.shape(trainarr)
trainarr[(trainarr)==0]
result = np.all((trainarr == 0), axis=0)
trainarr=np.delete(trainarr, [41,48,53,54,56,69,91,113,115,119,122,124,139], axis=1)
x=trainarr
testarr=np.delete(testarr,[41,48,53,54,56,69,91,113,115,119,122,124,139], axis=1)
result = np.all((trainarr == 0), axis=0)
print('Columns that contain only zero:')
for i in range(len(result)):
    if result[i]:
        print('Column: ', i)
result1 = np.all((testarr == 0), axis=0)
print('Columns that contain only zero:')
for i in range(len(result1)):
    if result1[i]:
        print('Column: ', i)

Columns that contain only zero:
Columns that contain only zero:


In [ ]:
#Normalization of the values of features (Not PARAMETERS)
#x=trainarr
x_mean=np.mean((x), axis=0)
x_std=np.std((x), axis=0)
x_std=np.reshape(x_std,(1,-1))
#print(x_std)
x=(x-x_mean)/(x_std)
#print(trainarr[(x_max-x_min)==0])
#print((x_std)[(x_std)==0])
#adding X0=1 for 1st parameter
arr_of_ones=np.ones((x.shape[0],1))
x=np.hstack((arr_of_ones,x))
x

array([[ 1.        ,  0.07252926, -0.22970849, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385,  0.48344326, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        ,  0.07252926, -0.08707814, ..., -0.09940535,
        -0.05425922, -0.07011719],
       ...,
       [ 1.        ,  1.49345392, -1.27566438, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385, -0.46742574, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385, -0.27725194, ..., -0.09940535,
        -0.05425922, -0.07011719]])

In [ ]:
print(y) #y has the saleprice of training dataset
x[np.isnan(x)]

[208500 181500 223500 ... 266500 142125 147500]


array([], dtype=float64)

In [ ]:
y1_mean=np.mean((y1), axis=0)
y1_mean.shape
y1_std=np.std((y1), axis=0)
y1_normalize=(y1-y1_mean)/(y1_std)
y1_normalize.shape

(1022,)

In [ ]:
arrp=np.zeros((x.shape[1],1))
learn_rate=0.0001

#reshaping of y was necessary as it was in 1D array form. So, by below reshaping, it will be converted to 2D array.
y1_nor=np.reshape(y1_normalize,(-1,1)) #-1 means it will automatically take the number of rows of y
#so, we DONT NEED to see and put it there, MANUALLY.

#running of number of iterations
for z in range(5000):
  #losses=0
  for j in range(x.shape[1]): #to iterate through each column for parameter modification
                    #, b=34 columns
    #arrp1=np.array(arrp,dtype='int32')
    pred=np.matmul(x,arrp)
    #print(pred)
    #mul=np.array(mul,dtype='int32') 
    sum=0 #taken here because, for each parameter editing, the sum need to be 0
      #as we will be calculating and modifying each parameter 
    sum=np.sum(np.matmul((x.T[j]),((pred-y1_nor))))

    #print(np.shape(sum))
    #print(sum)
    arrp[j][0]=arrp[j][0]-((learn_rate)*(sum)) #modification of each parameters
    #print(arrp)
  loss=np.sum(((pred-y1_nor)**2))/y1_nor.shape[0]
  #losses+=loss
  #loss1.append(loss)
  print(loss)

Streaming output truncated to the last 5000 lines.
0.2672490161834447
0.18288262999500107
0.158693963899934
0.14596575850378823
0.13777383530713191
0.13202156608353638
0.12775300764757996
0.12445597611736273
0.1218305476234139
0.1196893452498584
0.11790910608168004
0.11640525292254968
0.11511770189574526
0.11400252412107886
0.1130268255861394
0.11216547929825507
0.11139896713990509
0.1107119107192038
0.11009204408887933
0.10952947837703994
0.1090161645676661
0.10854549413156504
0.10811199768455962
0.10771111470924327
0.10733901565903542
0.10699246322945787
0.10666870327420593
0.10636537839319107
0.10608045901559551
0.10581218808872245
0.10555903642134833
0.10531966642270382
0.10509290249530119
0.10487770672977756
0.10467315884646507
0.10447843955551264
0.10429281668241386
0.10411563354142161
0.1039462991449479
0.1037842799196602
0.10362909266489048
0.10348029854016219
0.10333749790917728
0.10320032589983037
0.10306844856553095
0.10294155955371148
0.10281937720396905
0.1027016420116567


In [ ]:
print(arrp)

[[ 1.20439769e-16]
 [ 2.92768937e-02]
 [ 2.30431248e-02]
 [ 4.91006118e-02]
 [ 1.71184495e-01]
 [ 6.91172853e-02]
 [ 9.79899641e-02]
 [ 2.90357957e-02]
 [ 5.63007412e-02]
 [ 9.70966989e-02]
 [ 2.03745432e-02]
 [-1.21172873e-02]
 [ 8.58860847e-02]
 [ 7.98336337e-02]
 [ 1.14538135e-01]
 [-7.60494299e-03]
 [ 1.42164183e-01]
 [ 1.32545720e-02]
 [-7.96556099e-03]
 [ 2.34495154e-02]
 [ 1.49874962e-02]
 [-4.73830946e-02]
 [-8.79249432e-02]
 [ 1.27304311e-01]
 [ 8.82060522e-02]
 [-3.26442266e-02]
 [ 4.96593126e-02]
 [ 6.33922089e-02]
 [ 3.98753717e-02]
 [-7.81976579e-03]
 [ 1.62806733e-02]
 [ 4.95258687e-03]
 [ 3.50897372e-02]
 [-9.03120900e-03]
 [ 3.09339253e-04]
 [-1.71054317e-02]
 [-1.16904882e-02]
 [-4.32155627e-03]
 [-2.17369174e-02]
 [-3.77575344e-02]
 [ 5.47004866e-03]
 [-1.44702739e-02]
 [-5.71119575e-03]
 [ 1.27921414e-03]
 [-3.62114548e-02]
 [-1.11539508e-01]
 [-1.14648771e-01]
 [ 6.12180638e-03]
 [ 2.99511890e-02]
 [-5.48088790e-03]
 [-1.21306642e-01]
 [-1.53434574e-01]
 [ 3.8573276

In [ ]:
#normalization of testarr
testarr_mean=np.mean((testarr), axis=0)
testarr_std=np.std((testarr), axis=0)
testarr=(testarr-testarr_mean)/testarr_std
testarr_ones=np.ones((testarr.shape[0],1))
testarr=np.hstack((testarr_ones,testarr))
testarr

array([[ 1.        ,  1.48755151, -1.14252399, ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533, -0.02285264, ..., -0.04789131,
        14.7478812 , -0.04789131],
       [ 1.        , -0.86688533, -0.02492056, ..., -0.04789131,
        -0.06780635, -0.04789131],
       ...,
       [ 1.        ,  0.31033309, -0.19049144, ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533, -0.107706  , ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533,  0.18204304, ..., -0.04789131,
        -0.06780635, -0.04789131]])

In [ ]:
y_pred=np.matmul(testarr,arrp)
#Here I have created another object data2, because, I want to get the value of X-axis of the graph which I have plotted below
data2=pd.read_csv('/content/drive/MyDrive/dataset/sample_submission.csv')
arr8=data2.to_numpy()
arrx=arr8[:,0] #done only to plot the graph, this will be x-axis
print(arrx) 

[1461. 1462. 1463. ... 2917. 2918. 2919.]


In [ ]:
y_pred

array([[ 1.04481257e-01],
       [ 1.38081930e+00],
       [-6.63200177e-01],
       [-2.72802504e-01],
       [ 1.50153869e+00],
       [-1.05392460e+00],
       [-7.27177458e-01],
       [-5.32384518e-01],
       [ 9.24087889e-01],
       [ 1.21552332e+00],
       [ 7.70727595e-01],
       [-1.10035997e+00],
       [-1.12219885e+00],
       [ 1.77297510e+00],
       [ 9.87406349e-01],
       [-1.09109303e+00],
       [-1.60319711e+00],
       [ 3.84491828e-02],
       [-2.07966911e-01],
       [ 2.72868152e-02],
       [ 1.03383141e+00],
       [ 2.70684559e+00],
       [-2.88646408e-01],
       [ 2.40901761e+00],
       [-2.70572385e-01],
       [-2.23598049e-01],
       [-9.97487764e-01],
       [ 1.87087977e-01],
       [ 2.85082396e-01],
       [ 6.98776813e-03],
       [-2.65879256e-01],
       [ 9.24954437e-01],
       [-1.52463775e-01],
       [ 3.27115501e-01],
       [ 7.52305150e-01],
       [ 2.18122844e+00],
       [ 5.04672981e-01],
       [ 1.51118869e-01],
       [-9.7

In [ ]:
y2_mean=np.mean((y2), axis=0)
y2_mean.shape
y2_std=np.std((y2), axis=0)
y2_normalize=(y2-y2_mean)/(y2_std)
y2_normalize.shape

(437,)

In [ ]:
#Normalized loss value
p1=np.sum((y2_normalize-y_pred)**2)
q1=np.sum((y2_normalize-y2_mean)**2)
r21=1-(p1/q1)
r21

0.9999999744784622