<a href="https://colab.research.google.com/github/ayush572/House_price_prediction_model/blob/main/House_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [1]:
#New training model started from here
#first run this cell please
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#One hot encoding done here
#Training of model
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/dataset/train.csv')
dummies=pd.get_dummies(df, columns=['MSZoning','HeatingQC','CentralAir','BsmtQual','BsmtCond','ExterQual','Exterior1st','RoofStyle','KitchenQual','Street','LandContour','GarageType','Utilities','LotConfig','FireplaceQu','GarageQual','GarageCond','BsmtFinType1','LandSlope','LotShape','Condition1','PoolQC','Fence','MiscFeature','SaleType','BldgType','HouseStyle','SaleCondition','RoofMatl'], drop_first=True)
y=df.SalePrice
y=y.to_numpy()
df=df.drop(['SalePrice','Id','MSZoning','CentralAir','Electrical','BldgType','HouseStyle','Heating','Street','HeatingQC','BsmtFinType2','BsmtQual','Alley','Functional','BsmtFinType1','BsmtCond','Foundation','SaleCondition','LandContour','ExterQual','Fireplaces','FireplaceQu','GarageCond','GarageQual','LandSlope','Neighborhood','Condition1','Condition2','LotShape','PoolQC','Fence','SaleType','RoofMatl','MiscFeature','BsmtExposure','ExterCond','MasVnrType','Utilities','LotConfig','GarageFinish','PavedDrive','Exterior2nd','GarageType','Exterior1st','RoofStyle','KitchenQual'], axis=1)
df=pd.concat([dummies], axis=1)
df.drop(['Functional','Id','Alley','Neighborhood','Condition2','Exterior2nd','MasVnrType','ExterCond','Foundation','BsmtExposure','BsmtFinType2','Heating','Electrical','GarageFinish','PavedDrive'], axis=1, inplace=True)
df.drop(df.columns[36], inplace=True, axis=1)
df=df.fillna(df.mean())
#Here the specific columns have been removed, upon comparision with the TEST DATASET
df.drop(df.columns[[152,153,154,155]], axis=1, inplace=True)
df.drop(['HouseStyle_2.5Fin'], axis=1, inplace=True)
df.drop(['MiscFeature_TenC'], axis=1, inplace=True)
df.drop(['PoolQC_Fa'], axis=1, inplace=True)
df.drop(['GarageQual_Fa'], axis=1, inplace=True)
df.drop(['Utilities_NoSeWa'], axis=1, inplace=True)
df.drop(['Exterior1st_ImStucc','Exterior1st_Stone'], axis=1, inplace=True)
df.drop(['MSZoning_FV'], axis=1, inplace=True)
df.head()
#df.info(verbose=True, null_counts=True)

MSSubClass  LotFrontage  ...  RoofMatl_WdShake  RoofMatl_WdShngl
0          60         65.0  ...                 0                 0
1          20         80.0  ...                 0                 0
2          60         68.0  ...                 0                 0
3          70         60.0  ...                 0                 0
4          60         84.0  ...                 0                 0

[5 rows x 147 columns]

In [3]:
train=df[:1022]
test=df[1023:]
y1=y[:1022]
y2=y[1023:]

In [4]:
trainarr=train.to_numpy()
testarr=test.to_numpy()
import numpy as np
#m,n=np.shape(trainarr)
trainarr[(trainarr)==0]
result = np.all((trainarr == 0), axis=0)
trainarr=np.delete(trainarr, [41,48,53,54,56,69,91,113,115,119,122,124,139], axis=1)
x=trainarr
testarr=np.delete(testarr,[41,48,53,54,56,69,91,113,115,119,122,124,139], axis=1)
result = np.all((trainarr == 0), axis=0)
print('Columns that contain only zero:')
for i in range(len(result)):
    if result[i]:
        print('Column: ', i)
result1 = np.all((testarr == 0), axis=0)
print('Columns that contain only zero:')
for i in range(len(result1)):
    if result1[i]:
        print('Column: ', i)

Columns that contain only zero:
Columns that contain only zero:


In [5]:
#Normalization of the values of features (Not PARAMETERS)
#x=trainarr
x_mean=np.mean((x), axis=0)
x_std=np.std((x), axis=0)
x_std=np.reshape(x_std,(1,-1))
#print(x_std)
x=(x-x_mean)/(x_std)
#print(trainarr[(x_max-x_min)==0])
#print((x_std)[(x_std)==0])
#adding X0=1 for 1st parameter
arr_of_ones=np.ones((x.shape[0],1))
x=np.hstack((arr_of_ones,x))
x

array([[ 1.        ,  0.07252926, -0.22970849, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385,  0.48344326, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        ,  0.07252926, -0.08707814, ..., -0.09940535,
        -0.05425922, -0.07011719],
       ...,
       [ 1.        ,  1.49345392, -1.27566438, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385, -0.46742574, ..., -0.09940535,
        -0.05425922, -0.07011719],
       [ 1.        , -0.87475385, -0.27725194, ..., -0.09940535,
        -0.05425922, -0.07011719]])

In [6]:
print(y) #y has the saleprice of training dataset
x[np.isnan(x)]

[208500 181500 223500 ... 266500 142125 147500]


array([], dtype=float64)

In [7]:
y1_mean=np.mean((y1), axis=0)
y1_mean.shape
y1_std=np.std((y1), axis=0)
y1_normalize=(y1-y1_mean)/(y1_std)
y1_normalize.shape

(1022,)

In [9]:
arrp=np.zeros((x.shape[1],1))
learn_rate=0.0001

#reshaping of y was necessary as it was in 1D array form. So, by below reshaping, it will be converted to 2D array.
y1_nor=np.reshape(y1_normalize,(-1,1)) #-1 means it will automatically take the number of rows of y
#so, we DONT NEED to see and put it there, MANUALLY.

#running of number of iterations
for z in range(5000):
  #losses=0
  for j in range(x.shape[1]): #to iterate through each column for parameter modification
                    #, b=34 columns
    #arrp1=np.array(arrp,dtype='int32')
    pred=np.matmul(x,arrp)
    #print(pred)
    #mul=np.array(mul,dtype='int32') 
    sum=0 #taken here because, for each parameter editing, the sum need to be 0
      #as we will be calculating and modifying each parameter 
    sum=np.sum(np.matmul((x.T[j]),((pred-y1_nor))))

    #print(np.shape(sum))
    #print(sum)
    arrp[j][0]=arrp[j][0]-((learn_rate)*(sum)) #modification of each parameters
    #print(arrp)
  #loss=np.sum(((pred-y1_nor)**2))/y1_nor.shape[0]
  #losses+=loss
  #loss1.append(loss)
  #print(loss)

In [10]:
#normalization of testarr
testarr_mean=np.mean((testarr), axis=0)
testarr_std=np.std((testarr), axis=0)
testarr=(testarr-testarr_mean)/testarr_std
testarr_ones=np.ones((testarr.shape[0],1))
testarr=np.hstack((testarr_ones,testarr))
testarr

array([[ 1.        ,  1.48755151, -1.14252399, ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533, -0.02285264, ..., -0.04789131,
        14.7478812 , -0.04789131],
       [ 1.        , -0.86688533, -0.02492056, ..., -0.04789131,
        -0.06780635, -0.04789131],
       ...,
       [ 1.        ,  0.31033309, -0.19049144, ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533, -0.107706  , ..., -0.04789131,
        -0.06780635, -0.04789131],
       [ 1.        , -0.86688533,  0.18204304, ..., -0.04789131,
        -0.06780635, -0.04789131]])

In [11]:
y_pred=np.matmul(testarr,arrp)
#Here I have created another object data2, because, I want to get the value of X-axis of the graph which I have plotted below
data2=pd.read_csv('/content/drive/MyDrive/dataset/sample_submission.csv')
arr8=data2.to_numpy()
arrx=arr8[:,0] #done only to plot the graph, this will be x-axis
print(arrx) 

[1461. 1462. 1463. ... 2917. 2918. 2919.]


In [12]:
#normalized predicted prices
#y_pred

In [13]:
y2_mean=np.mean((y2), axis=0)
y2_mean.shape
y2_std=np.std((y2), axis=0)
y2_normalize=(y2-y2_mean)/(y2_std)
y2_normalize.shape

(437,)

In [14]:
#Normalized loss value
p1=np.sum((y2_normalize-y_pred)**2)
q1=np.sum((y2_normalize-y2_mean)**2)
r21=1-(p1/q1)
r21

0.9999999744784622